<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>storm rule</name>
  <uuid>9db6f244-ed4d-404b-98fe-8a498c5dcf3d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Weather is storm alert
then
	set decision to "Stay home. There is a storm alert" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
